ARG PYCLOWDER_PYTHON="3"
FROM maxzilla2/extractors-simple-extractor:se

ENV EXTRACTION_FUNC="ply2las"
ENV EXTRACTION_MODULE="transformer"

# Install applications we need
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3-gdal \
        gdal-bin

# Install Python updates
RUN python3 -m pip install --upgrade --no-cache-dir pip
RUN python3 -m pip install --upgrade --no-cache-dir setuptools
RUN python3 -m pip install --upgrade --no-cache-dir \
        numpy \
        influxdb \
        laspy \
        requests==2.21.0 \
        python-dateutil \
        utm \
        matplotlib \
        Pillow \
        scipy \
        cryptography \
        pyclowder

RUN apt-get install -y --no-install-recommends \
        libgdal-dev \
        gcc \
        g++ \
        python3-dev && \
    python3 -m pip install --upgrade --no-cache-dir \
        pygdal==1.11.3.5 && \
    apt-get remove -y \
        libgdal-dev \
        gcc \
        g++ \
        python3-dev && \
    apt-get autoremove -y

COPY extractor_info.json /home/extractor